### ISSUE TITLE
No sky rendering under Linux with latest build

### ISSUE THREAD

**Issue by poVoq** [eukara/FreeCS#19]
While the sky works fine in the FTEQW build from May (and under Windows running with WINE), the latest FTEQW linux build (with both the vulkan and the OGL renderer) stopped rendering the skyboy textures.

**Comment by eukara** [comment]
This is related to the engine, not FreeCS itself. I will forward this to Spike.

**Comment by poVoq** [comment]
Yeah, I wish FTEQW had a proper public issue tracker on github or gitlab :(

Is it possible that the skyboxes use jpg or PNG textures? Lately the dynamic libary linking with Ubuntu breaks all the time...

**Comment by eukara** [comment]
Due to legal reasons, I am avoiding shipping any content related to Half-Life.
(Aside from the menu, which temporarily uses tga textures because BMP support is currently disabled in FTEQW, but the font isn't theirs anyway and the splash is expendable).
Feel free to convert the skyboxes to TGA yourself with GIMP or ImageMagick, that format doesn't require a dynamic library. Don't worry, the people in power know what needs to be done for these issues to be addressed. :)

**Comment by eukara** [comment]
Okay, seems like some maps have missing skies due to the case-sensitive nature of the file-system.
In maps like dust it will look for /gfx/env/desbk.tga, but CS 1.5 ships with /gfx/env/**d**esbk.tga which will cause the file to not be found.

I suggest renaming the textures until Spike adds a way to load files in a case-insensitive manner

**Comment by poVoq** [comment]
yeah that seems to do the trick.

**Comment by eukara** [comment]
Supposedly with fs_cache enabled (that's the default) the file system will be read case-insensitive. It obviously does not work right now so that will be fixed soonish
