### ISSUE TITLE
FTEQW forks

### ISSUE THREAD

**Issue by TheBrainScrambler** [eukara/FreeCS#31]
I'm a bit confused about FTEQW since I saw 3 different projects having that name:
- https://fteqw.org with source https://www.github.com/fte-team/fteqw: you linked to that one
- https://vcs.vera-visions.com/tech/engine: this is the version of fteqw that the Nuclide SDK will pull when you are trying to build it with the build_engine.sh script. It looks the same as https://www.github.com/fte-team/fteqw since they have the same last commit and the same amount of commits, but can't say for sure though
- https://fte.triptohell.info with source at https://sourceforge.net/p/fteqw/code/HEAD/tree/: this one is clearly different, the commits and the README are already different

Also checking https://fte.triptohell.info/resources it says that FreeCS is supported, but links to a sourceforge project at https://sourceforge.net/projects/freecs-1-5/. The author is named eukara so I assume it's you ?

So what versions of FTEQW are actually compatible with FreeCS ? I'm asking because my distro ships with https://fte.triptohell.info already so using that one would make things easy for me.

I've also tested this FTEQW with FreeCS. If I use your releases of FreeHL and FreeCS, set them up with the assets and run fteqw on them, it seems to work fine. FreeHL is bugged but you said that's normal in its README, and FreeCS looks like it's working apart from some weird visual glitches when looking outside of the map.
However trying to compile FreeHL and FreeCS doesn't work with that fteqcc. When trying to build FreeHL using the Makefile in src, I get this:
```
cd client && make
make[1]: Entering directory '/tmp/freecs/nuclide/valve/src/client'
fteqcc progs.src
FTEQCC: Jan  1 1980
Source file: progs.src
Outputfile: ../../csprogs.dat
including ../../../src/shared/fteextensions.qc
including ../../../src/shared/defs.h
../../../src/shared/NSIO.h:30: error: expected ;, found (
../../../src/shared/NSTrigger.h:56: error: expected ;, found (
../../../src/shared/NSEntity.h:89: error: expected ;, found (

************ ERROR ************
virtual keyword on member that is not a function
Error in ../../../src/shared/NSIO.h on line 30
make[1]: *** [Makefile:4: all] Error 1
make[1]: Leaving directory '/tmp/freecs/nuclide/valve/src/client'
make: *** [Makefile:4: all] Error 2
```
(yes it's normal that fteqcc says it was built on Jan 1 1980)
I'm using the rev 6303 of that fteqw/fteqcc.

**Comment by eukara** [comment]
You need to build FreeCS with a relatively recent version of FTEQCC. Due to the constant needs for new extensions and bugfixes, we often update the engine. There's also lots of changes I had to do to the compiler to make this all possible.

All the named above versions of FTEQW are the same. I host fteqw.org. triptohell is maintained by Spike to some extent (he's not hosting it) but he has a large archive of files there that people might want. It's a bit overwhelming and so fteqw.org exists to be a simple boarding experience.
The vcs.vera-visions.com repo is the one Spike actively works in and commits to when it's not GitHub. So far I push to GitHub myself whenever he pushes to vcs.vera-visions.com because of some auth restrictions Spike needs to figure out in his own time. I also push things from GitHub to there to keep things in sync.

We used to keep things on SourceForge for some time. They've actively made the experience more miserable for both users and developers. It's also discouraged contributions, so SourceForge is more or less being abandoned.

**Comment by TheBrainScrambler** [comment]
https://fte.triptohell.info/ links to the sourceforge version though. So does it just mean that the website is outdated ?
Also for an updated upstream for the FTEQW package should I use https://www.github.com/fte-team/fteqw or https://vcs.vera-visions.com/tech/engine ?

**Comment by eukara** [comment]
I'd recommend using the GitHub URL for the best uptime

**Comment by TheBrainScrambler** [comment]
Ok, thanks !
