### ISSUE TITLE
How do you actually play?

### ISSUE THREAD

**Issue by billbeans** [eukara/freecs#44]
The readme explains nothing. Am I supposed to use my Half-Life install from Steam? I don't think you could have written less helpful instructions if you tried

**Comment by eukara** [comment]
> The readme explains nothing. Am I supposed to use my Half-Life install from Steam?

You will need a copy of [FTE QuakeWorld](http://www.fteqw.org/) for your platform. Place that in the root of your Half-Life game directory, that’s where your **hl.exe** normally is.

Then the 'Install' instructions from the `README.md` and `instructions.txt` apply. Download and move the two .pk3 files I provide into valve/ and cstrike/ respectively. A reworded version of all this can also be found [here on this website](https://www.frag-net.com/projects.html)

Any version of Half-Life should work. However the FreeCS component is for CS 1.5. Missing assets will have substitutes (the Steam version does not have all the content from the CD-ROM version).
 There's differences between maps and models, but those generally do not affect Counter-Strike. They might bite you when playing on protected servers on HLDM however). That's why I generally recommend people grab and patch the CD-ROM version. It also is not at risk of being updated by Valve.

> I don't think you could have written less helpful instructions if you tried

I should probably just link to the Frag-Net page. People coming from the FreeHL or other pages generally haven't had issues setting it up.

**Comment by billbeans** [comment]
That would probably explain why using my Steam install was so buggy. I didn't have the main menu background screen shown on the git front page, Dust 2 had a black skybox, and I was missing a knife animation, to name a few. Are there any active servers? I only saw one
