### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by Mistrick** [eukara/FreeCS#46]

**Comment by eukara** [comment]
Engine is built from here
https://sourceforge.net/p/fteqw/code/HEAD/tree/
cd into the engine directory, and issue 'make m-rel'

**the game-logic does not need to be built...** but can be if desired.
that's also on the svn repo above.

then run fteqcc inside the Source/Menu, Source/Server and Source/Client folders.

**Comment by Shpoike** [comment]
svn checkout https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk fteqw && cd fteqw/engine && make makelibs && make m-rel -j4 && release/fteqw -basedir ~/freecs
will checkout, compile dependancies, compile fteqw, and run.
is the theory. if you want to dynamically link to your system libraries then skip the makelibs part, but you'll need to set them up properly first.
there's a couple of cross-compile scripts to manage dependencies and targets and stuff, but they're not really end-user-safe right now, but should be okay on debian and maybe ubuntu.

to compile fteqcc, cd engine && make qcc-rel
again you'll find an fteqcc binary inside the engine/release subdir.
The compiled gamecode is OS neutral and bundled by freecs, so you only need the qcc if you want to make actual changes to it.

The plugins-rel target also exists if you want to build the optional plugins too (the xmpp plugin can offer NAT hole punching for private games, but otherwise the plugins are not that useful for freecs).

*-dbg targets also exist, if you want stack traces or gdb or whatever. binaries are instead written to the engine/debug but otherwise basically the same.
'make help' should show you the documented targets.

cross compiling from linux or cygwin to native win32 can be done by adding FTE_TARGET=win32 to make's commandline, assuming you have mingw64 installed etc. FTE_TARGET=win64 for a win64 build.


but yeah, no autoconf, nor cmake etc, simpler for me, but special annoying specialness for other people. sorry about that. lately I've been thinking I ought to rewrite large chunks of the makefile but I'm too lazy to fix everything that it would break.

**Comment by voidhoschi** [comment]
I assume, the fteqcc abstracts operating-specific stuff away through ftequake.  Can you tell me, which file(s) in the bundle are actually the result from fteqcc?

**Comment by eukara** [comment]
freecs/progs.dat = Results from compiling Source/Server with fteqcc
freecs/csprogs.dat = From Source/Client
freecs/menu.dat = From Source/Menu

progs.dat is the server-side game-logic, where all the things being networked run in. csprogs.dat is responsible for the Heads-Up-Display. A copy of the servers csprogs.dat will actually be sent to clients if they join a server. It's for security mainly... but that way admins can make HUD modifications as well.

**Comment by voidhoschi** [comment]
Thanks :simple_smile:
