### ISSUE TITLE
Cannot fire, jump or crouch while VGUI is opened

### ISSUE THREAD

**Issue by Calinou** [eukara/FreeCS#63]
One cannot fire, jump or crouch while the VGUI is opened (the menu used for voice commands). If you hold the jump key, the client will jump, but the server won't acknowledge the action, which means that your view will jitter up and down.

Tested in a local game and on a remote server.

**Comment by eukara** [comment]
I completely suppress those input_buttons being networked fully, because then clicks would register as you trying to shoot the weapon while using the buymenu. An exception will be made for the voice commands menu to shoot. The other buttons will be unlocked in the next commit.

As for the jumping, that's a seperate problem and is related to how input is perceived on the client with the prediction system. A fix will be issued to prevent SPACE from being held down and acting that way.

**Comment by eukara** [comment]
Was fixed back in 
https://github.com/eukara/FreeCS/commit/9938e339e90e761bc990884d1b5d6b25f362ea50
