### ISSUE TITLE
A few questions..

### ISSUE THREAD

**Issue by thejustsoul** [eukara/FreeCS#80]
- How to set maxplayers (slots)
(`maxplayers 32 and sv_playerslots 32 crashed server`)
- How to set opus codec for voice
I tried to use the following settings
```
cl_voip_opus_bitrate "128000"
cl_voip_codec 2
cl_voip_test 1
bind k +voip
```
And after press k, view error in console:
`Unable to use opus codec - not installed`.

- How to make a auto map change over time, timelimit doesn't help
- How to disable sounds after minimize game (borderless window)
- How to reduce CPU usage when the game is minimized (when you start the game in window without frame), now it rests around 50%, even if you're in the observers.
- How to fix very slow move after press shift and move on left-right

There are still a lot of questions, but to solve at least these :)

**Comment by Shpoike** [comment]
you can find a libopus-0.dll for win32 here: https://archive.mozilla.org/pub/opus/win32/opusfile-v0.9-win32.zip (it needs the gcc dependency dll too) that should work iiuc.
unfortunately everyone else needs a copy too.
speex is still the default on account of that being the only codec that ezquake also supports, although that's of no benefit to freecs. I should probably just statically link both for a while.

sv_playerslots overrides the default slot count, with a maximum value of 255 (normally defaults to 0 in singleplayer and 32 otherwise).
maxclients and maxspectators control how many of each is allowed to join, but I suspect freecs bypasses that somewhat.
if that's crashing then that's serious... doesn't seem to be a problem for me though.

snd_inactive 0; will no longer play sounds while the window is not focused (on some systems anyway). needs a snd_restart though. unfortunately the freecs menus lack a few things like this. you can hit ctrl+c to kill the freecs menus and that'll leave you with the engine's ugly art-less ones (menu_restart console command to get the freecs menu back). the engine menus should be a little more complete with regard to audio etc, including devices, but much of it might not apply.

regarding inactive cpu, set cl_idlefps to something low like 10 and the engine will sleep between ticks.
you can also set cl_yieldcpu to 1 to reduce cpu usage with vsync off (or with low cl_maxfps).

**Comment by thejustsoul** [comment]
@Shpoike 
- if need to all people manual copy this dll, is bad -(
Im copy to game dir (where fteqw64.exe) only `libopus-0.dll` and all *.dll from archive, but not solved problem..
- cvar `maxclients` is work and not crash server
- cvar `snd_inactive 0` not solved problem if game run in borderless window and open game menu
- cvar `cl_idlefps 10` is work, but after setting the value, all the servers in the menu now have ping > 100, if set to 30, ping for all >30 this bug?
